use std::error::Error;

pub async fn initiate_google_oauth() -> Result<(), Box<dyn Error>> {

	Ok(())
}
